### ISSUE TITLE
Can't execute kubectl without oauth device prompt after running this

### ISSUE THREAD

**Issue by JohnGalt1717** [Azure/aks-set-context#63] opened 2022-05-24 16:55 UTC
I have the following:

```
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.BETA_AZURE_CREDENTIALS }}
      - uses: azure/setup-kubectl@v2.0
      - uses: azure/aks-set-context@v2.0
        with:
          resource-group: ${{ secrets.BETA_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.BETA_AKS_CLUSTER }}
      - run: kubectl -n pltfrmd set image deployments/account account=${{ secrets.BETA_ACR_SERVER }}/account:${{ github.sha }} 

```

From everything I've read, the implication is that after using aks-set-context you can then run kubectl commands. But when I run this, I get a prompt to open a web browser with a code in the action logs. I've verified all of the variables are set correctly, but no joy. Please provide documentation on how we'd use this to execute a kubectl command reliably.

**Comment by JohnGalt1717** [comment] 2022-06-13 14:28
I'm not sure what else I can give you. If you do the above, you get a notice in logs to open a URL in a browser with a device code just like any other kubectl attempt that isn't authenticated. It just then sits there forever unless you manually open a browser with that url and device code and do it for it.

As for OIDC auth, it's a disaster area at the moment with bad documentation, no install instructions on windows (only mac!?!) and it doesn't work reliably.  But one would assume that the azure/login uses statement would do this properly per the documentation already.

**Comment by Syed-Mudassir-Uddin** [comment] 2022-06-15 13:27
@JohnGalt1717 , setting 'admin' flag to true in the action azure/aks-set-context@v2 worked for me.

- uses: azure/aks-set-context@v2.0
        with:
          resource-group: ${{ secrets.BETA_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.BETA_AKS_CLUSTER }}
          admin: true

**Comment by OliverMKing** [comment] 2022-06-21 13:08
We also have another solution for non-admin users with the [Kubelogin](https://github.com/Azure/aks-set-context#kubelogin) scenario.

**Comment by OliverMKing** [comment] 2022-07-06 14:31
Going to close this for now. If the issue is still happening please reopen.

**Closed by OliverMKing** 2022-07-06 14:31 UTC
Labels: question, idle
